### ISSUE TITLE
No blog subscribe option

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#13]
All blog entries should have a subscribe button prominently displayed so that users can subscribe to future blog entries.

At the same time - we need to migrate all current budgie-remix.org subscribers over.

**Comment by GrindamN** [comment]
Regarding that, it will be possible, but only with subscription box at bottom of each post. Follow system is basically available to only Wordpress.com hosted blogs and those on that network. Box will be added.

**Comment by GrindamN** [comment]
Working on it, would be awesome if we could get CSV list so that we could auto import it. @fossfreedom .

**Comment by fossfreedom** [comment]
@GrindamN see Gitter link

**Comment by fossfreedom** [comment]
close in favour of #19
