### ISSUE TITLE
switch (forward) budgie-remix.org to ubuntu-budgie.org

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#14]
placeholder - date at which we need to switch-over is Beta 2 23rd March

Confirmation that all current website issues need to be resolved by this date.

This is a go-no-go decision.  on this date we'll either switch to ubuntu-budgie.org or revert to wordpress and forward ubuntu-budgie.org requests to wordpress.

**Comment by GrindamN** [comment]
On it. Prepared a backup just in case something goes wrong.
