### ISSUE TITLE
Add IRC

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#16]
like ubuntu-mate.org/irc lets add a similar irc page to our new channel #ubuntu-budgie - it wouldnt be accessed via the menu but maybe via the symbols in the footer

**Comment by fossfreedom** [comment]
use new icon from budgie-welcome

**Comment by GrindamN** [comment]
The icon refers to the support page. Due to nature of support page and its future use to explain various communication channel, adding IRC icon would yield no visual benefit.
