### ISSUE TITLE
add google translate to the website

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#17]
https://translate.google.com/manager/website/add

We should think about adding the above or equivalent since most of our users do not speak english as their first language.

**Comment by GrindamN** [comment]
Added

**Comment by quassy** [comment]
For me the Google Translate bar is off-putting and makes the Ubuntu Budgie website look cheap. Also my browser is set to accept `de` and `en` so it shouldn't actually be there. In my opinion this features belongs to the client side and should not be integrated into websites (just imagine every website integrating some form of automated translation tool...).

For languages I don't understand I manually use a browser extension (Firefox) or the integrated translation tools (Chrome), which provide the same translation but don't look as bad and respect user preferences about if and when something should be translated.
