### ISSUE TITLE
budgie-remix website UI Mockup

### ISSUE THREAD

**Issue by uD4ra** [budgie-remix/budgie-remix.github.io#2]
Hello everyone,
**I just created Mockup for budgie-remix website.** Please take a look at them and let me know about your Ideas & opinions about my Mockup for make it better :smile: 

> Note : All content texts are demo texts, not the actual words, if you have any opinions for better Ideas I'm so glad to hear them.

Thanks.

![budgie-remix](https://cloud.githubusercontent.com/assets/12265797/14875462/0822ac68-0d1c-11e6-9422-9a05bfd3fd1e.png)

**Comment by thatcriticguy** [comment]
That looks really sharp although you'd want to avoid using the word "securer". Otherwise I think it's quite beautiful. You also never put a comma before an and as in the sentence "for the past couple of months, and" - I'd be happy to assist with wording, etc.

**Comment by uD4ra** [comment]
Aha ok, Thanks for your opinion :) I'll fix it.

**Comment by uD4ra** [comment]
Closed this because of we're not building a website using this mockup.
