### ISSUE TITLE
potential broken links

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#20]
ok - website switchover date is rapidly approaching ... we are not quite there at the moment.

Worried about the blog site vs what we have on wordpress.  The blog links do not map directly to ubuntubudgie.org - different folder names.  What we can't have is lots of broken links from sites that have linked to us.

Need to link the wordpress relative paths to the equivalent on the new site so that pages get redirected correctly.

very high importance.

**Comment by GrindamN** [comment]
Fixed.
