### ISSUE TITLE
create a how to install page

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#21]
Needs to be prominently displayed on the Downloads page (possibly)

https://www.ubuntu.com/download/desktop/install-ubuntu-desktop

at a high-level

    Check the recommended system requirements
    Download the ISO.
    Burn a DVD or create a bootable USB stick
    Boot from the DVD or USB stick to check your computer is compatible with Ubuntu
    Back up your important files (in the unlikely event that the installation fails)
    Install Ubuntu Budgie

**Comment by GrindamN** [comment]
Under development
