### ISSUE TITLE
add ubuntu trademark statement

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#23]
important:

look at the bottom of ubuntu-mate.org - in their footer very small text there is a ubuntu trademark statement.  We will need the same.

    Ubuntu is a trademark of Canonical Ltd. ubuntubudgie.org is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. Contents © 2017 Ubuntu Budgie Team.

**Comment by GrindamN** [comment]
Added.
