### ISSUE TITLE
Downloads page needs a revamp

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#24]
I've just looked at the Ubuntu Mate Downloads page - They list horizontally the versions to install.  clicking on a version displays what the version is.

Further clicking displays the download options (torrent vs ISO), Download Tip, OS Disc, Getting Started, Mirrors.

Definitely very well designed - very clean.  

We will have 3 or 4 versions in April, 16.04.2, 16.10, 17.04, 17.04 "Fresh" - so we need to cover these by reworking the current page.

**Comment by GrindamN** [comment]
Working on it.

**Comment by vincenzob1** [comment]
Just finished it with the new downloads buttons/layout
