### ISSUE TITLE
[suggestion] Support Us rename to Contribute

### ISSUE THREAD

**Issue by ericoporto** [budgie-remix/budgie-remix.github.io#3]
The content under support us and team are too similar, with exception of the patreon/paypal links.
Support Us should be renamed to Contribute to avoid confusion.
You ask for money but gives no incentives (what would the money enable?) and claim transparency but don't show a money_in/money_out breakdown.
I would suggest move things that are general help (like bug reporting, translation, support on forums), stuff that are continuous (you would be doing now, next year, and five year from now in a regular base, to contribute too.

So with this, keep opportunities for one shot things, and bitesize stuff  (maybe come up with some minimal card system that clearly points to bug tracker, code piece, has tags) , and also having a small guideline on how to do those contributions.

**Comment by fossfreedom** [comment]
support-us page updated to show extra info.

**Comment by GrindamN** [comment]
Done.
