### ISSUE TITLE
Lowercase 'i' on features page

### ISSUE THREAD

**Issue by luk3yx** [budgie-remix/budgie-remix.github.io#31]
I have found a lowercase 'i' on the [features page](https://ubuntubudgie.org/features), in the sentence "_Hey, you! welcome! How may i help you?_".

![_Hey, you! welcome! How may i help you?_](https://cloud.githubusercontent.com/assets/3182651/25161877/900f7c0a-2512-11e7-935d-ed6c57781164.png)

**Comment by GrindamN** [comment]
Fixed.
