### ISSUE TITLE
Fly me to the moon

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#37]
Twitter reports that the link has been hit by a copyright request and is not working from the US

**Comment by GrindamN** [comment]
Weird. I've checked it out, works fine here. Can anyone test it by using US proxy?

**Comment by fossfreedom** [comment]
ok - tested at work.

The proxy we use goes through germany

![untitled](https://user-images.githubusercontent.com/996240/27741776-203b006e-5dae-11e7-9258-eda89c93d679.png)
