### ISSUE TITLE
Links are difficult to see

### ISSUE THREAD

**Issue by ericoporto** [budgie-remix/budgie-remix.github.io#4]
![image](https://cloud.githubusercontent.com/assets/2244442/21463148/6c387ec0-c94c-11e6-845f-5c0d56630ac6.png)

![image](https://cloud.githubusercontent.com/assets/2244442/21463167/9e534098-c94c-11e6-8687-a4a65cc66a6d.png)

The links in the website are hidden, this makes navigating a bit harder. I would suggest leaving they always with the style used on mouse over.

**Comment by deadbaed** [comment]
the website moved to https://ubuntubudgie.org so but this issue is still revelant. @Udara-U3 @fossfreedom @Foggalong @HEXcube maybe create a new repo dedicated to issue for the new website?

**Comment by GrindamN** [comment]
This issue has been fixed. Check the pages, posts containing links to see how it looks. Be sure to clear your cache.
