### ISSUE TITLE
Packages preinstalled in the Distro should be listed in the website

### ISSUE THREAD

**Issue by ericoporto** [budgie-remix/budgie-remix.github.io#5]
When I install this distro, what will be preinstalled? This should be clearly stated somewhere!

**Comment by GrindamN** [comment]
About the application list, possible, package list? More suited for wiki or some listing separated from main view. Btw the list is already available on Launchpad.

**Comment by fossfreedom** [comment]
aye - the full list is here - rather lengthy!

http://bazaar.launchpad.net/~ubuntubudgie-dev/ubuntu-seeds/ubuntu-budgie.zesty/view/head:/desktop

**Comment by ericoporto** [comment]
I was thinking more apps people commonly use and link to the complete list. Why some stuff is between parenthesis? 

Apps I was thinking about were :

- libreoffice

- transmission

- chromium 

- gedit

- evince 

- file-roller

- gnome-calendar

- gnome-screenshot

- gnome-software

An addition I think would be useful is some really simple software to edit images, like MS Paint, so people can screenshot things and edit to highlight stuff they will send to a friend when asking for help and similar simple use cases.

**Comment by fossfreedom** [comment]
stuff in parenthesis are recommended packages vs dependencies - its a packaging thing.

Yeah - have been thinking about a nice MS Paint style app - GIMP is too complex - Pinta is nice - but it is Mono - so the dependency list is too large.

**Comment by niyasc** [comment]
**Note**
Ubuntu MATE has a [*What is Ubuntu MATE*](https://ubuntu-mate.org/what-is-ubuntu-mate/) page which lists commonly used applications available in distribution and that is just a copy of [*introduction*](https://github.com/UbuntuBudgie/budgie-welcome/blob/master/data/introduction.html) page in Welcome App.
