### ISSUE TITLE
 HTTPS required by Chrom/ium for future downloading

### ISSUE THREAD

**Issue by BryanQuigley** [budgie-remix/budgie-remix.github.io#52]
Cdimage has added HTTPS support so you can switch downloads to that.   Might also be beneficial to switch from torrents to magnet links (doesn't require hitting any server to start the download).

More backstory is here: https://bugs.launchpad.net/ubuntustudio-website/+bug/1862428

**Comment by GrindamN** [comment]
Fixed.
