### ISSUE TITLE
Who is your target audience?

### ISSUE THREAD

**Issue by ericoporto** [budgie-remix/budgie-remix.github.io#6]
By looking the distro, the website and everything, I have no idea for who this is. The website doesn't make easy to install (how do I make a thumbdriver? (maybe link etcher, rust, unetbootin, ...)), so doesn't look this is for beginners, the distro comes with generic default package - not focusing in creative, like Krita, Blender, Ardour, Kdenlive, instead showing Libreoffice, which would suggest the domestic usage? 

I am very confused on why this project exists. Which motivated you guys to go for a full blown distro instead of DE only? I am just asking things to motivate you guys to reflect on the objectives, mission, value, this things are very important since they will guide the project.

**Comment by deadbaed** [comment]
well the DE already exists, and this is the distro that uses it by default, like ubuntu gnome, it uses gnome as DE by default (this is why different flavors of ubuntu exist btw)

**Comment by fossfreedom** [comment]
Words to be included somewhere (maybe front and central)

"Ubuntu Budgie is a proud official member of the Ubuntu family.  We combine the simplicity and elegance of the Budgie interface to produce a traditional desktop orientated distro with a modern paradigm.  Fully functional out of the box, we include the best available Linux applications that makes you (our community) productive immediately.  Backed by the powerful Debian derived Ubuntu repositories, customisation is just a point-and-click allowing you to tailor the desktop to your way of working."
