### ISSUE TITLE
website landing page is wrong for small mobiles

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#7]
![](https://files.gitter.im/ubuntubudgie/k7er/website.jpg)

5 inch mobile 480 x 854 pixels (~218 ppi pixel density)

**Comment by ericoporto** [comment]
It looks just like in not so small mobiles 1920x1080, 403dpi

**Comment by GrindamN** [comment]
Can you take screenshot for better view? I believe it works by pressing rocker buttons (the ones for switching songs) at the same time. Also if anyone has similar issue, please post it here. I need to see if it is browser specific or global issue.

**Comment by ericoporto** [comment]
![screenshot_20161225-090144](https://cloud.githubusercontent.com/assets/2244442/21470815/c1901ccc-ca80-11e6-96c8-7fea6ce7fd15.png)

Here it is

**Comment by fossfreedom** [comment]
![screenshot_2016-12-25-10-59-03](https://cloud.githubusercontent.com/assets/996240/21470848/43e5ca8a-ca92-11e6-9c53-ee4efa859ec6.png)

seems to be a general header issue.

**Comment by GrindamN** [comment]
Hmm, I can fix problem to some degree but on even smaller screens, I would have to reduce hamburger menu so it could fit.

**Comment by GrindamN** [comment]
Fixed
