### ISSUE TITLE
contact us is not a help page

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix.github.io#8]
"Please provide us with your email so we can give you answer to your question"

this implies that this is a help page 

The page should start with a link to all the social media outlets - state these are where you get help.

The contact us page is for all issues that are NOT distro help issues.

**Comment by GrindamN** [comment]
Fixed. Now it reads: Please provide us with your email to respond

**Comment by fossfreedom** [comment]
better :) - just need to add to the top of the page the social media links and statement that these are where you get help  ... take the icons on the community page in budgie-welcome
